import type { Metadata } from "next";
import { Geist, Geist_Mono, Epilogue, } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import localFont from 'next/font/local';
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const epilogue = Epilogue({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-epilogue",
});
const clashDisplay = localFont({ 
  variable: "--font-clash-display",
  src: [
    { path: "./fonts/clash-font/ClashDisplay-Semibold.otf", weight: "600", style: "normal" },
  


  ]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${epilogue.variable} ${clashDisplay.variable} antialiased`}
      >
        <Header />
        {children}

        <Footer />
      </body>
    </html>
  );
}
